config/routes.rb
Rails.application.routes.draw do

  devise_for :users
root 'home#index'

resources :posts, except: :index
resources :comments
resources :authors, only: [:show, :index, :edit]
resources :users
resources :articles, only: [:show, :index]
end

app/models/article.rb
class Article < ActiveRecord::Base
validates :post_id, presence: true
belongs_to :post
end

app/models/author.rb
class Author < ActiveRecord::Base
validates :nickname, presence: true
validates :nickname, length: { minimum: 3 }
validates :user_id, presence: true
before_create :set_postcounter
belongs_to :user
	protected
	def set_postcounter
		self.postcounter = 0
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
validates :content, presence: true
validates :post_id, presence: true
validates :author_id, presence: true
belongs_to :post
belongs_to :author
end

app/models/post.rb
class Post < ActiveRecord::Base
validates :content, presence: true
validates :title, presence: true
validates :author_id, presence: true
belongs_to :author
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :trackable, :validatable
	has_one :author
	after_create :create_author_for_user

	private
	def create_author_for_user
		author=Author.new
		author.nickname = self.email
		author.user_id=self.id
		author.save
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
#coding UTF-8

class ArticlesController < ApplicationController
	def index
		@articles = Article.all
		@authors = Author.all
		@posts = Post.all 
		@comments = Comment.all

	end
	def show
		@article=Article.find(params[:id])
		@post = Post.find(@article.post_id)
		@authors = Author.all
		@comments = Comment.where(post_id: @post.id)
	end



	private 
	def article_params
		params.require(:article).permit(:post_id)
	end
end

app/controllers/authors_controller.rb
#coding UTF-8

class AuthorsController < ApplicationController
	before_action :authenticate_user!
	def index
		@authors = Author.all

	end
	def show
		@author=Author.find(params[:id])
	end
	# def destroy
	# 	@author=Author.find(params[:id])
	# 	@author.destroy
	# 	redirect_to authors_path, alert: "usunieto"
	# end
	# def new
	# 	@author=Author.new

		
	# end
	# def create
	# 	if Author.create(author_params)
	# 		redirect_to authors_path, notice: "utowrzono nowy"
	# 	else
	# 		render 'new'
	# 	end
	# end
	def edit
		@author=Author.find(params[:id])
		make_sure_its_mine

	end
	def update
		@author=Author.find(params[:id])
		if @author.update(author_params)
			redirect_to authors_path, notice: "zmieniono"
		else
			render 'edit'
		end

	end



	private 
	def author_params
		params.require(:author).permit(:nickname)
	end

    def make_sure_its_mine
      unless current_user.author.id==params[:id].to_i
        redirect_to root_url, alert: "Brak uprawnień"
      end
      true
    end
end

app/controllers/comments_controller.rb
#coding UTF-8

class CommentsController < ApplicationController
	def index
		@authors = Author.all
		@posts = Post.all 
		@comments = Comment.all

	end
	def show
		@author=Author.all
		@comment=Comment.find(params[:id])
	end
	def destroy
		unless current_user.author.id==params[:id].to_i
        	redirect_to root_url, alert: "Brak uprawnień"
        else
        	@comment=Comment.find(params[:id])
			@comment.destroy
			redirect_to posts_path, alert: "usunieto"
      	end
		
	end
	def new
		@comment=Comment.new

		
	end
	def create
		@comment = Comment.new(comment_params)
		@comment.author_id = current_user.author.id
		@comment.post_id = params[:comment][:post_id]
		if @comment.save
			redirect_to articles_path, notice: "utworzono nowy"
		else
			render 'new'
		end
	end
	def edit
		unless current_user.author.id==params[:id].to_i
        	redirect_to root_url, alert: "Brak uprawnień"
        else
			@comment=Comment.find(params[:id])
      	end
		

	end
	def update
		@comment=Comment.find(params[:id])
		if @comment.update(comment_params)
			redirect_to articles_path, notice: "zmieniono"
		else
			render 'edit'
		end

	end



	private 
	def comment_params
		params.require(:comment).permit(:content, :author_id, :post_id)
	end
	# def make_sure_its_mine
 #      unless current_user.author.id==params[:id].to_i
 #        redirect_to root_url, alert: "Brak uprawnień"
 #      end
 #      true
 #    end
end

app/controllers/home_controller.rb
#coding: UTF-8

class HomeController < ApplicationController
	def index
		@post = Post.first
	end
end

app/controllers/posts_controller.rb
#coding UTF-8

class PostsController < ApplicationController
	before_action :authenticate_user!
	
	def index
		@posts = Post.all

	end
	def show
		@author=Author.all
		@post=Post.find(params[:id])
	end
	def destroy
		@post=Post.find(params[:id])
		unless @post.author.id == current_user.author.id
         	redirect_to root_url, alert: "Brak uprawnień"
         else 
         	@post.destroy
         	redirect_to root_url, alert: "usunięto"
       	end
	end
	def new
		@post=Post.new
	end
	def create
		@post = Post.new(post_params)
		@post.author_id = current_user.author.id

		if @post.save
			@article = Article.create(post_id: @post.id)
			redirect_to posts_path, notice: "utworzono"
		else
			render 'new'
		end
	end
	def edit
		@post=Post.find(params[:id])
		unless @post.author.id == current_user.author.id
         	redirect_to root_url, alert: "Brak uprawnień"
       	end
	end
	def update
		@post=Post.find(params[:id])
		if @post.update(post_params)
			redirect_to posts_path, notice: "zmieniono"
		else
			render 'edit'
		end

	end



	private 
	def post_params
		params.require(:post).permit(:title, :content)
	end
	# def make_sure_its_mine(post)
	# 	unless post.author.id == current_user.author.id
 #        	redirect_to root_url, alert: "Brak uprawnień"
 #        else 
 #        	true
 #      	end
	# end
end

app/controllers/users_controller.rb
#coding UTF-8

class UsersController < ApplicationController
	before_action :authenticate_user!

  def index 
    redirect_to authors_path
  end
	def show
    make_sure_its_mine
		redirect_to author_path(current_user.author)
    #@user=current_user
	end

  private
    def make_sure_its_mine
      unless current_user.id==params[:id].to_i
        redirect_to root_url, alert: "To nie twoje konto!"
      end
      true
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.haml
%h1 Rozmowy
.container.col-sm-1
%dl.col-sm-10
  - @posts.each do |post|
    %h2
      = link_to post.title, article_path(@articles.where(post_id: post.id).first.id)
      %h3.col-sm-1
      %p.change-color-to-green
        = post.content
        %footer.allign-right
          Autor: 
          - if post.author_id!=nil
            = link_to @authors.find(post.author_id).nickname, author_path(post.author_id)
          - else
            = "Anon"

          
        - @comments.each do |comment|
          %br

          
          - if comment.post_id==post.id
            %p.col-sm-1
            = link_to comment.content, comment_path(comment.id)
            %br
            %p.allign-right
              Autor:
              - if comment.author_id!=nil
                = link_to @authors.find(comment.author_id).nickname, author_path(comment.author_id)
              - else
                = "Anon "
        
%hr
%p.col-sm-10
  = link_to "Utwórz rozmowę", new_post_path

app/views/articles/show.html.haml
%h1 Rozmowa
.container.col-sm-1
%dl.col-sm-10
  %dt
    = link_to @post.title , post_path(@post.id)
  %br
    %dd
      = @post.content
      .col-sm-1
      %p.allign-right
        Autor: 
        - if @post.author_id!=nil
          = link_to @post.author.nickname, author_path(@post.author.id)
        - else
          = "Anon"
      %br
      - @comments.each do |comment|
        %br
        %p.col-sm-1
        - if comment.post_id==@post.id
          %dd
          = link_to comment.content, comment_path(comment.id)
          %br
            %p.allign-right
              Autor: 
              - if comment.author_id!=nil
                = link_to @authors.find(comment.author_id).nickname, author_path(comment.author_id)
              - else
                = "Anon "
%hr

app/views/authors/edit.html.erb
<h1> edytuj autora </h1>
<%= form_for(@author) do |f| %>
		<%= f.label :nickname %>
	<%= f.text_field :nickname %>
	<%= f.submit "edytuj" %>
<% end %>

app/views/authors/index.html.haml
%h1 Autorzy naszego forum
%dl
  - @authors.each do |author|
    %br
    %dt.center
      = link_to author.nickname, author_path(author.id)

app/views/authors/new.html.erb
<!-- <h1> dodaj Autora </h1>
<%= form_for(@author) do |f| %>
	<%= f.label :nickname %>
	<%= f.text_field :nickname %>
	<%= f.submit "dodaj" %>
<% end %> -->

app/views/authors/show.html.erb
<h1><%= @author.nickname %> </h1>
<%= link_to "Edytuj", [:edit, @author] %>

app/views/comments/edit.html.erb
<h1> edytuj komentarz </h1>
<%= form_for(@comment) do |f| %>
		<%= f.label :Treść %>
	<%= f.text_field :content %>
	<%= f.submit "edytuj" %>
<% end %>

app/views/comments/index.html.erb
<!-- <h1> comcie </h1>
<% if alert%>
<p>Uwaga!: <%=alert%></p>
<% elsif notice %>
<p>generalnie spoko, ale : <%=notice%></p>
<% end %>
<dl>
<% @comments.each do |comment| %>
<dt>
	<%= @posts.find(comment.post_id).title %>
		<dd>
			<%= @posts.find(comment.post_id).content %>
			<%= link_to "Przejdź do", comment_path(comment.id) %>
			<p>posted by
			<% if @posts.find(comment.post_id).author_id!=nil %>
			<%= @authors.find(@posts.find(comment.post_id).author_id).nickname %>
			<% else %>
			<%= "Anon" %>
			<% end %></p>
		</dd>
	<dd>
		<%= comment.content %>
		<%= link_to "Przejdź do", comment_path(comment.id) %>
		<p>posted by
			<% if comment.author_id!=nil %>
			<%= @authors.find(comment.author_id).nickname %>
			<% else %>
			<%= "Anon" %>
			<% end %></p>
	</dd>
</dt>
<% end %>
</dl> -->

app/views/comments/new.html.erb
<h1> dodaj komentarz </h1>
<%= form_for(@comment) do |f| %>
	<%= f.label :Treść %>
	<%= f.text_field :content %>
	<%= f.hidden_field :post_id, value: params[:post_id]%>
	<%= f.submit "dodaj" %>
<% end %>

app/views/comments/show.html.erb
<h1 class="center"><%= @comment.content %></h1>
<p class="allign-right">
<%= link_to "Edytuj", [:edit, @comment] %>
<%= link_to "Usuń", comment_path(@comment.id), method: :delete %></p>
<p>Autor: 
<% if @comment.author_id!=nil %>
<%= link_to @comment.author.nickname, author_path(@comment.author.id) %>
<% else %>
<%= "Anon" %>
<% end %></p>

app/views/home/index.html.haml
.container
	.row
		.col-sm-3
		.col-sm-6
			%h1.text-center
			- if current_user
				%h1
					Witaj,
					\#{link_to current_user.author.nickname , current_user.author}
				%p.allign-right= link_to "przejdz do forum", articles_path
			- else
				%h1 
					Witaj, Anon
				%p.allign-right= link_to "zarejestruj się", new_user_registration_path
				%p.allign-right= link_to "zaloguj się", new_user_session_path
			

app/views/layouts/application.html.haml
%html
  %head
    %title Uber Blog 9000
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %div.center
      - if alert
        %p.change-color-to-red
          Uwaga: #{alert}
        %hr
      - elsif notice
        %p.change-color-to-orange
          Spokojnie: #{notice}
        %hr
    %div.allign-left
      \#{link_to "Główna" , root_url}
    - if current_user
      .allign-right.change-color-to-green
        Jesteś zalogowany jako 
        \#{link_to current_user.author.nickname , current_user.author}
        = link_to "wyloguj", destroy_user_session_path, method: :delete
      %hr
    = yield

app/views/posts/edit.html.erb
<h1> edytuj post </h1>
<%= form_for(@post) do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
		<%= f.label :content %>
	<%= f.text_field :content %>
	<%= f.submit "edytuj" %>
<% end %>

app/views/posts/index.html.erb
<h1> posty </h1>
<dl>
<% @posts.each do |post| %>
<dt>
	<%= post.title %>
	<dd>
		<%= link_to "Autor " + post.author.nickname, author_path(post.author_id) %>
		<%= link_to "Przejdź do rozmowy", post_path(post.id) %>
	</dd>
</dt>
<% end %>
</dl>

app/views/posts/new.html.erb
<h1> dodaj post </h1>
<%= form_for(@post) do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :content %>
	<%= f.text_field :content %>
	<%= f.submit "dodaj" %>
<% end %>

app/views/posts/show.html.erb
<h1 class="center"><%= @post.title %> </h1>
</br>
<p class="col-sm-10">
<%= @post.content %> </p>
</br>
<p class="col-sm-10">Autor: 
<% if @post.author_id!=nil %>
<%= link_to @author.find(@post.author_id).nickname, author_path(@post.author_id) %>
<% else %>
<%= "Anon" %>
<% end %></p>
<p class="col-sm-10">
<%= link_to "Edytuj", [:edit, @post] %>
<%= link_to "Usuń", post_path(@post.id), method: :delete %>
<%= link_to "Skomentuj", new_comment_path(post_id:@post.id) %></p>